name: pip_services3_aws
version: 1.0.0
author: Sergey Seroukhov <seroukhov@gmail.com>
description: This framework is part of the [Pip.Services](https://github.com/pip-services/pip-services) project. It contains components for AWS cloud platform.
homepage: https://github.com/pip-services3-dart/pip-services3-aws-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pip_services3_commons: ">=1.0.4 <2.0.0"
  pip_services3_components: ">=1.0.2 <2.0.0"
  pip_services3_container: ">=1.0.0 <2.0.0"
  aws_client: ^0.2.0
  aws_lambda_dart_runtime: ^1.0.3
  aws_cloudwatch_api: ^0.0.3
  aws_logs_api: ^0.0.1
 
dev_dependencies:
  test: '>=1.14.2 <2.0.0'